administration/urls.py
from django.conf.urls import url
from . import views

app_name = 'administration'
urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/minside/$', views.MyPageDetailView.as_view(), name='myPage'),
    url(r'nybruker/$', views.PersonCreateView.as_view(), name='personCreate'),
    url(r'brukere/$', views.PersonListView.as_view(), name='personList'),
    url(r'brukere/(?P<slug>[\w-]+)/$', views.PersonDetailView.as_view(), name="personDetail"),
    url(r'brukere/oppdater/(?P<slug>[\w-]+)/$', views.PersonUpdateView.as_view(), name='personUpdate'),
    url(r'skoler/$', views.SchoolListView.as_view(), name='schoolList'),
    url(r'skoler/(?P<school_pk>[0-9]+)/$', views.SchoolDetailView.as_view(), name="schoolDetail"),
    url(r'lagskole/$', views.SchoolCreateView.as_view(), name='schoolCreate'),
    url(r'skoler/oppdater/(?P<school_pk>[0-9]+)/$', views.SchoolUpdateView.as_view(), name='schoolUpdate'),
    url(r'skoler/oppdater/(?P<school_pk>[0-9]+)/leggtilklasse/$', views.GradeCreateView.as_view(), name='gradeCreate'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/$', views.GradeDetailView.as_view(),
        name='gradeDetail'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/oppdater/$', views.GradeUpdateView.as_view(),
        name='gradeUpdate'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/leggtilelev/$', views.PersonCreateView.as_view(),
        name='gradeAddStudent'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/leggtillærer/$', views.PersonCreateView.as_view(role=2),
        name='gradeAddTeacher'),
    url(r'mineklasser/$', views.GradeListView.as_view(), name='gradeList'),
    url(r'grupper/$', views.GroupListView.as_view(), name="groupList"),
    url(r'gruppe/(?P<group_pk>[0-9]+)/$', views.GroupDetailView.as_view(), name='groupDetail'),
    url(r'grupper/nygruppe/$', views.GroupCreateView.as_view(), name='groupCreate'),
    url(r'brukere/slett/(?P<slug>[\w-]+)/$', views.PersonDeleteView.as_view(), name='personDelete'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/(?P<slug>[\w-]+)/slett/$',
        views.PersonDeleteView.as_view(), name='personDeleteGrade'),
    url(r'gruppe/(?P<group_pk>[0-9]+)/oppdater/$', views.GroupUpdateView.as_view(), name='groupUpdate'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/gruppe/$', views.GroupCreateView.as_view(),
        name='gradeGroupCreate'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/(?P<slug>[\w-]+)/$',
        views.PersonDetailView.as_view(), name='PersonDetailFromGrade'),
]

maths/urls.py
from django.conf.urls import url
from . import views

app_name = 'maths'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'nyoppgave/$', views.TaskCreateView.as_view(), name='createTask'),
    url(r'nyoppgave/mappe/(?P<directory_pk>[0-9]+)/$', views.TaskCreateView.as_view(), name='createTaskDirectory'),
    url(r'equationEditor/$', views.EquationEditorView.as_view(), name='equationEditor'),
    url(r'oppgaver/$', views.TaskListView.as_view(), name='taskList'),
    url(r'oppgaver/(?P<task_pk>[0-9]+)/$', views.TaskDetailView.as_view(), name='taskDetail'),
    url(r'oppgaver/(?P<task_pk>[0-9]+)/slett/(?P<item_pk>[0-9]+)/$', views.ItemDeleteView.as_view(), name='itemDelete'),
    url(r'oppgaver/oppdater/(?P<task_pk>[0-9]+)/$', views.TaskUpdateView.as_view(), name='taskUpdate'),
    url(r'kategorier/$', views.CategoryListView.as_view(), name='categoryList'),
    url(r'kategorier/ny/$', views.CategoryCreateView.as_view(), name='categoryCreate'),
    url(r'kategorier/(?P<category_pk>[0-9]+)/oppdater/$', views.CategoryUpdateView.as_view(), name='categoryUpdate'),
    url(r'lagtest/$', views.TaskCollectionCreateView.as_view(), name='taskCollectionCreate'),
    url(r'tester/$', views.TaskCollectionListView.as_view(), name='taskCollectionList'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/$', views.TaskCollectionDetailView.as_view(),
        name='taskCollectionDetail'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/oppdater/$', views.TaskCollectionUpdateView.as_view(),
        name='taskCollectionUpdate'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/slett/$', views.TaskCollectionDeleteView.as_view(),
        name='taskCollectionDelete'),
    url(r'minetester/(?P<slug>[\w-]+)/$', views.TestListView.as_view(), name='testList'),
    url(r'minetester/(?P<slug>[\w-]+)/publiser/(?P<test_pk>[0-9]+)/$', views.TestListView.as_view(),
        name='testListPublish'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/slett/$', views.TestDeleteView.as_view(), name='testDelete'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/$', views.TestDetailView.as_view(), name='testDetail'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/(?P<grade_pk>[0-9]+)/klasse/$', views.TestDetailView.as_view(),
        name='testGradeDetail'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/(?P<group_pk>[0-9]+)/gruppe/$', views.TestDetailView.as_view(),
        name='testGroupDetail'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/publiser/$', views.TestCreateView.as_view(), name='testCreate'),
    url(r'test/(?P<test_pk>[0-9]+)/besvarelse/(?P<slug>[\w-]+)/$', views.AnswerListView.as_view(), name='answerDetail'),
    url(r'test/(?P<test_pk>[0-9]+)/besvarelse/public/(?P<user_id>[\w-]+)/$', views.AnswerListView.as_view(),
        name='answerDetailAnonymous'),
    url(r'test/(?P<test_pk>[0-9]+)/svar/$', views.AnswerCreateView.as_view(), name='answerCreate'),
    url(r'test/(?P<test_pk>[0-9]+)/eksporter/$', views.export_data, name='answerExport'),
    url(r'test/fullført/$', views.LinkSuccess.as_view(), name='answerFinished'),
    url(r'eksportering/$', views.ExportData.as_view(), name='exportData'),
    url(r'oppgaver/mappe/matistikk/$', views.DirectoryDetailView.as_view(), name='directoryRoot'),
    url(r'oppgaver/mappe/(?P<directory_pk>[0-9]+)/$', views.DirectoryDetailView.as_view(), name='directoryDetail'),
    url(r'oppgaver/mapper/slett/$', views.DirectoryDelete.as_view(), name='directoryDelete'),
    url(r'oppgaver/mapper/endre/$', views.DirectoryEdit.as_view(), name='directoryEdit'),
    url(r'oppgaver/mapper/flytt/$', views.DirectoryMove.as_view(), name='directoryMove'),
    url('r/oppgaver/logg/$', views.TaskLogView.as_view(), name='taskLog'),
    url('r/oppgaver/logg/slett/$', views.TaskLogDeleteView.as_view(), name='taskLogDelete'),
    url(r'test/(?P<answer_id>[0-9]+)/besvarelse/$', views.AnswerDetailView.as_view(), name='answerGET'),

]

matistikk/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from maths import views as mathViews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^matistikk/', include('maths.urls', namespace='maths')),
    url(r'^administrasjon/', include('administration.urls', namespace='administration')),
    url(r'^$', mathViews.IndexView.as_view(), name='index'),
    url(r'login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': '/'}, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/models.py
"""The models that are mainly used in the administration app"""

# Core Django imports
from django.db import models
from django.contrib.auth.models import User, Group
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.core.urlresolvers import reverse



class School(models.Model):
    """A school


    :school_admin: The person responsible for the school.
    :school_name: The name of the school.
    :school_address: The address of the school.
    :is_active: Value that says if the school is active or not.

    """
    school_administrator = models.ForeignKey('Person', null=True, blank=True, verbose_name='Skoleadministrator',
                                             help_text='Ikke påkrevd. Opprett en ny skoleadministrator ved å trykke på plusstegnet til høyre.',
                                             on_delete=models.SET_NULL)
    school_name = models.CharField(max_length=100, verbose_name='Navn')
    school_address = models.CharField(max_length=100, verbose_name='Adresse')
    is_active = models.BooleanField(default=True, verbose_name='aktiv',
                                    help_text='Angir at denne skolen er aktiv. Avmerk denne i stedet for å slette skolen.')

    class Meta:
        ordering = ['school_name']

    def __str__(self):
        return self.school_name

    def get_absolute_url(self):
        """
            Function that sets the absolute_url.
        """
        return reverse('administration:schoolDetail', kwargs={'school_pk': self.id})


class Grade(models.Model):
    """ A grade is a group of students

    :school: The school object the grade relates to
    :grade_name: The name name of the grade
    :tests: Which tests this class has been given access to.
    :is_active: Value that says if the school is active or not.

    """
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    grade_name = models.CharField(max_length=100, verbose_name='klassenavn')
    tests = models.ManyToManyField('maths.Test', blank=True, verbose_name='tester')
    is_active = models.BooleanField(default=True, verbose_name='aktiv',
                                    help_text='Angir at denne klassen er aktiv. Avmerk denne i stedet for å slette klassen.')

    class Meta:
        ordering = ['school_id', 'grade_name']

    def __str__(self):
        return self.school.school_name + " - " + self.grade_name


class Person(AbstractUser):
    """A person is a customUser model, it contains information about the user that does not relate to user-management.

    :grades: The grades this person is registered to.
    :Sex: The sex of the person.
    :Date_of_birth: The persons date of birth.
    :Role: The role this user has in the system.

    """

    grades = models.ManyToManyField(Grade, default="", blank=True, verbose_name="klasse")
    SEX = [
        ("M", "Gutt"),
        ("F", "Jente")
    ]
    ROLE = [
        (1, "Elev"),
        (2, 'Lærer'),
        (3, 'Skoleadministrator'),
        (4, 'Administrator')
    ]
    sex = models.CharField(max_length=1, choices=SEX, verbose_name="kjønn", null=True)
    date_of_birth = models.DateField(max_length=8, verbose_name='Fødselsdato', null=True)
    role = models.IntegerField(choices=ROLE, default=1, verbose_name='brukertype')
    tests = models.ManyToManyField('maths.Test', blank=True, verbose_name='tester')

    class Meta:
        ordering = ['username']

    def __str__(self):
        return self.first_name + " " + self.last_name + " - " + self.username

    def get_absolute_url(self):
        """
            Function that sets the absolute_url.
        """
        return reverse('administration:personDetail', kwargs={'slug': self.username})

    def create_username(self):
        """
            Function that generates a username based on the first and last name.
        """
        first_name_form = self.first_name
        last_name_form = self.last_name
        first_name = first_name_form.replace(" ", "")
        first_name_lower = first_name.lower()
        last_name_lower = last_name_form.lower()
        last_name_tab = str.split(last_name_lower)
        username = first_name_lower
        for letter in last_name_tab:
            username += letter[0]
        last_name_list = list(last_name_tab[-1])
        for letter in last_name_list[1:]:
            if Person.objects.filter(username__exact=username):
                username += letter
            else:
                self.username = username
                break
        counter = 1
        username_correct = username
        while Person.objects.filter(username__exact=username_correct):
            username_correct = username + str(counter)
            counter += 1
        return username_correct


class Gruppe(models.Model):
    """ A Group is a group of students

     :creator: The creator of the group.
     :persons: The persons in this group.
     :group_name: The name of the group.
     :is_active: Value that says if the group is active or not.
     :visible: Value that says if the group should be visible to its members or not.

     """
    creator = models.ForeignKey(Person, verbose_name='Ansvarlig', related_name='+')
    persons = models.ManyToManyField(Person, blank=True, verbose_name='Medlemmer')
    group_name = models.CharField(max_length=100, verbose_name='Gruppenavn')
    is_active = models.BooleanField(default=True, verbose_name='aktiv',
                                    help_text='Angir at denne gruppen er aktiv. Avmerk denne i stedet for å slette gruppen.')
    visible = models.BooleanField(default=False, verbose_name="synlig",
                                  help_text='Angir om gruppen skal være synlig for sine medlemmer.')
    grade = models.ForeignKey(Grade, blank=True, null=True, verbose_name='klasse', help_text='Ikke påkrevd.')
    tests = models.ManyToManyField('maths.Test', blank=True, verbose_name='tester')

    class Meta:
        ordering = ['group_name']

    def __str__(self):
        if self.grade:
            return self.group_name + " - " + self.grade.__str__()
        else:
            return self.group_name


# This is in order to have different names shown by the django-forms than variable-names
Person._meta.get_field('username').verbose_name = 'brukernavn'
Person._meta.get_field('first_name').verbose_name = 'fornavn'
Person._meta.get_field('last_name').verbose_name = 'etternavn'
Person._meta.get_field('is_staff').verbose_name = 'lærer'
Person._meta.get_field('email').verbose_name = 'Epost'

administration/forms.py
from django import forms
from .models import Grade, Person, School


class PersonForm(forms.ModelForm):
    """
    Form used to create a new person.

    :First_name: Persons first name.
    :Last_name: Persons last name.
    :Email: Persons email.
    :Date_of_Birth: Persons date of birth.
    :Sex: Persons sex.
    :Is_active: Decides if the Person is active or not. Used instead of deleting the Person.
    :Grades: Which grades the person are in.
    :Role: Persons role in the system.

    """
    first_name = forms.CharField(required=True, label='Fornavn')
    last_name = forms.CharField(required=True, label='Etternavn')

    class Meta:
        """
            Bases the form on the Person model
        """
        model = Person
        fields = ['first_name', 'last_name', 'email', 'date_of_birth', 'sex', 'is_active', 'grades', 'role']


class FileUploadForm(forms.Form):
    """
    Form used to upload excel file with Person information.

    :File: The file that will be uploaded.

    """
    file = forms.FileField()

    def __init__(self, *args, **kwargs):
        """
            Adds help text to the file field when initiated.
        """
        super(FileUploadForm, self).__init__(*args, **kwargs)
        self.fields['file'].help_text = 'Aksepterte filformat: .xls, .xlsx, .ods, .csv'


class ChangePasswordForm(forms.ModelForm):
    """
    Form used to change the password to a Person.

    :Password: New password for the Person.
    :Password2: New repeated password for the Person.

    """

    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        """
            Bases the form on the Person model
        """
        model = Person
        fields = ['password']


class SchoolForm(forms.ModelForm):
    """
    Form used to create a school.

    :School_name: Name of the school.
    :School_address: Address of the school.
    :School_administrator: Person responsible for the school.
    :Is_active: Decides if the School is active or not. Used instead of deleting the School.

    """

    class Meta:
        """
        Bases the form on the School model.
        """
        model = School
        fields = ['school_name', 'school_address', 'school_administrator', 'is_active']

    def __init__(self, *args, **kwargs):
        """
        Changes the queryset to only match persons with the role 3, so only school administrators can be appointed.

        """
        super(SchoolForm, self).__init__(*args, **kwargs)
        self.fields['school_administrator'].queryset = Person.objects.filter(role=3)


class SchoolAdministratorForm(forms.ModelForm):
    """
    Form used to create a school administrator.

    :First_name: The school administrators first name.
    :Last_name: The school administrators last name.
    :Email: The school administrators email.
    :Date_of_birth: The school administrators date of birth.
    :Sex: The school administrators sex.
    """
    first_name = forms.CharField(required=True, label='Fornavn')
    last_name = forms.CharField(required=True, label='Etternavn')
    email = forms.EmailField(required=True, label='Epost')

    class Meta:
        """
            Bases the form on the Person model.
        """
        model = Person
        fields = ['date_of_birth', 'sex']

administration/templates/administration/gradeList.html
{% extends 'matistikk/base.html' %}

{% block body %}
    <table class="table table-hover table-striped table-responsive" id="classtable">
        <thead>
        <tr>
            <th>Klasse</th>
        </tr>
        </thead>
        <tbody>
        {% for grade in object_list %}
            <tr class="clickable-row"
                data-href="{% url 'administration:gradeDetail' school_pk=grade.school_id pk=grade.id %}"
                style="cursor: pointer">
                <td>{{ grade }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <script>
        /**
         * This function makes the rows of the user-, student-, teacher- and admintable clickable
         */
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.document.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

administration/templates/administration/grade_form.html
<!--Extends the base.html file that includes different imports and the navbar-->
{% extends 'matistikk/base.html' %}
<!--Loads the tag library-->
{% load bootstrap3 %}
<!-- Loads CSS and javascript-->
{% bootstrap_css %}
{% bootstrap_javascript %}
<!--Display django.contrib.messages as Bootstrap alerts-->
{% bootstrap_messages %}
{% block body %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>Klasseadministrasjon</h2>
        </div>
        <div class="panel-body">
            <form class="form-horizontal form-margin" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary" id="addGradeBtn">
                        {% bootstrap_icon "check" %} Lagre
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

administration/templates/administration/grade_list.html
<!--Extends the base.html file that includes different imports and the navbar-->
{% extends 'matistikk/base.html' %}

{% block body %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>Mine klasser</h2>
            <div class="input-group">
                    <span class="input-group-addon">
                            <i class="fa fa-search"></i>
                        </span>
                <input type="text" class="form-control" id="search" onkeyup="gradeSearch()"
                       placeholder="Søk etter klasse">
            </div>
        </div>
        <div class="panel-body">
            <table class="table table-hover table-striped table-responsive" id="gradetable">
                <thead>
                <tr>
                    <th>Klassenavn</th>
                    <th>Skole</th>
                </tr>
                </thead>
                <tbody>
                {% for grade in object_list %}
                    <tr class="clickable-row"
                        data-href="{% url 'administration:gradeDetail' school_pk=grade.school_id grade_pk=grade.id %}"
                        style="cursor: pointer">
                        <td>{{ grade.grade_name }}</td>
                        <td>{{ grade.school }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script>
        /**
         * This function makes the rows of the user-, student-, teacher- and admintable clickable
         */
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.document.location = $(this).data("href");
            });
        });
    </script>

    <script>
        /**
         * This function matches the text in the search field with the content in the table with all grades
         * and removes rows that don't match the search criteria.
         */
        function gradeSearch() {
            var input, filter, table, tr, td, i;
            input = document.getElementById("search");
            filter = input.value.toUpperCase();
            table = document.getElementById("gradetable");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                td1 = tr[i].getElementsByTagName("td")[1];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1 || td1.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
{% endblock %}

administration/templates/administration/school_form.html
<!--Extends the base.html file that includes different imports and the navbar-->
{% extends 'matistikk/base.html' %}
<!--Loads the tag library-->
{% load bootstrap3 %}
<!-- Loads CSS and javascript-->
{% bootstrap_css %}
{% bootstrap_javascript %}
<!--Display django.contrib.messages as Bootstrap alerts-->
{% bootstrap_messages %}
{% block body %}

    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>Skoleadministrasjon</h2>
        </div>
        <div class="panel-body">
            <form class="form-horizontal form-margin" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_field form.school_name addon_before='<span class="glyphicon glyphicon-home"></span>' %}
                {% bootstrap_field form.school_address addon_before='<span class="fa fa-map-marker"></span>' %}
                {% bootstrap_field form.school_administrator addon_before='<span class="glyphicon glyphicon-user"></span>' addon_after='<a data-toggle="modal" data-target="#addAdministrator" style="cursor: pointer;" id="addNewSchoolAdministratorBtn"><span id="createPerson" class="glyphicon glyphicon-plus"></span></a>' %}
                <div class="alert alert-success hidden" id="successMessageDiv">
                    <strong>Fullført!</strong>
                </div>
                {% bootstrap_field form.is_active %}
                <button type="submit" class="btn btn-success hidden" id="saveNewSchoolBtn">
                </button>
            </form>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-success" onclick="submit()" id="saveNewSchoolBtnVisible">
                {% bootstrap_icon "check" %} Lagre
            </button>
        </div>
    </div>

    <script>
        /**
         * Function that runs when the document is ready, and hides the modalError div.
         */
        $(document).ready(function () {
            $("#modalError").hide();
            /**
             * Function that prevents the default submit and does an ajax-post call instead to create a new
             * school administrator user.
             */
            $('#schoolAdministratorForm').submit(function (e) {
                e.preventDefault();
                var first_name = $.trim($('#id_first_name').val());
                var last_name = $.trim($('#id_last_name').val());
                var email = $.trim($('#id_email').val());
                var date_of_birth = $.trim($('#id_date_of_birth').val());
                var sex = $.trim($('#id_sex').val());
                $.ajax({
                    type: 'POST',
                    url: '{% url 'administration:schoolCreate' %}',
                    data: {
                        'first_name': first_name,
                        'last_name': last_name,
                        'email': email,
                        'date_of_birth': date_of_birth,
                        'sex': sex,
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                    },
                    dataType: 'json',
                    success: success,
                    error: error
                });
            });

        });
        /**
         * Function that clicks the saveNewSchoolBtn button.
         */
        var schoolSubmitted = false;
        function submit() {
            if(schoolSubmitted){
                return 0;
            }
            $('#saveNewSchoolBtn').click();
            schoolSubmitted = true;
        }
        /**
         * Function that clicks the administratorCreate button.
         */
        var administratorSubmitted = false;
        function modalsubmit() {
            if(administratorSubmitted){
                return 0;
            }
            $('#administratorCreate').click();
            administratorSubmitted = true;
        }
        /**
         * Function that runs when the ajax-post call is successful and shows some successfields.
         */
        function success(data) {
            var field = $('#id_school_administrator');
            if (data.message) {
                errorMessage(data.message);
            }
            else {
                field.append($("<option></option>").attr("value", data.id).text(data.first_name + " " + data.last_name + " - " + data.username));
                field.find('option[value="' + data.id + '"]').prop("selected", true);
                $('#successMessageDiv').append(data.first_name + " " + data.last_name + " ble lagt til med brukernavnet " + data.username)
                $('#addAdministrator').modal('hide');
                $("#successMessageDiv").removeClass("hidden");
                $("#successMessageDiv").fadeTo(5000, 500).slideUp(500, function () {
                    $("#selectTaskWarning").slideUp(500);
                });
                $("#modalError").hide();
            }
        }
        /**
         * Function that runs when the ajax-post call is not successful and prints out the errormessage.
         */
        function error(xhr) {
            alert(xhr.responseText)
        }
        /**
         * Function that shows error messages.
         */
        function errorMessage(message) {
            $("#modalError").show();
            $('#liError').remove();
            $('#errorMessage').append("<li id='liError'>" + message + "</li>")
            $("#modalError").fadeTo(5000, 500).slideUp(500, function () {
                $("#modalError").slideUp(500);
            });
        }
    </script>
{% endblock %}
{% block modal %}
    <!-- Modal -->
    <div class="modal fade" id="addAdministrator" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Opprett administrator</h4>
                </div>
                <div class="modal-body">
                    <div id='modalError' class="alert alert-danger">
                        <strong>Noe gikk desverre galt.</strong>
                        <ul id="errorMessage"></ul>
                    </div>
                    <div class="form-margin">
                        <form id='schoolAdministratorForm' class="form-horizontal" action="" method="POST"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_field administratorForm.first_name addon_before='<span class="glyphicon glyphicon-user"></span>' %}
                            {% bootstrap_field administratorForm.last_name addon_before='<span class="glyphicon glyphicon-user"></span>' %}
                            {% bootstrap_field administratorForm.email addon_before='<span class=""><strong>@</strong></span>' %}
                            {% bootstrap_field administratorForm.date_of_birth addon_before='<span class="glyphicon glyphicon-calendar"></span>' placeholder='dd.mm.yyyy' %}
                            {% bootstrap_field administratorForm.sex addon_before='<span class="fa fa-venus-mars"></span>' %}
                            <button id='administratorCreate' type="submit" class="hidden">
                            </button>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id='administratorCreateVisible' type="button" class="btn btn-success"
                            onclick="modalsubmit()">
                        {% bootstrap_icon "check" %} Lagre
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Lukk</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}