maths/urls.py
from django.conf.urls import url
from . import views

app_name = 'maths'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'nyoppgave/$', views.TaskCreateView.as_view(), name='createTask'),
    url(r'nyoppgave/mappe/(?P<directory_pk>[0-9]+)/$', views.TaskCreateView.as_view(), name='createTaskDirectory'),
    url(r'equationEditor/$', views.EquationEditorView.as_view(), name='equationEditor'),
    url(r'oppgaver/$', views.TaskListView.as_view(), name='taskList'),
    url(r'oppgaver/(?P<task_pk>[0-9]+)/$', views.TaskDetailView.as_view(), name='taskDetail'),
    url(r'oppgaver/(?P<task_pk>[0-9]+)/slett/(?P<item_pk>[0-9]+)/$', views.ItemDeleteView.as_view(), name='itemDelete'),
    url(r'oppgaver/oppdater/(?P<task_pk>[0-9]+)/$', views.TaskUpdateView.as_view(), name='taskUpdate'),
    url(r'kategorier/$', views.CategoryListView.as_view(), name='categoryList'),
    url(r'kategorier/ny/$', views.CategoryCreateView.as_view(), name='categoryCreate'),
    url(r'kategorier/(?P<category_pk>[0-9]+)/oppdater/$', views.CategoryUpdateView.as_view(), name='categoryUpdate'),
    url(r'lagtest/$', views.TaskCollectionCreateView.as_view(), name='taskCollectionCreate'),
    url(r'tester/$', views.TaskCollectionListView.as_view(), name='taskCollectionList'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/$', views.TaskCollectionDetailView.as_view(),
        name='taskCollectionDetail'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/oppdater/$', views.TaskCollectionUpdateView.as_view(),
        name='taskCollectionUpdate'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/slett/$', views.TaskCollectionDeleteView.as_view(),
        name='taskCollectionDelete'),
    url(r'minetester/(?P<slug>[\w-]+)/$', views.TestListView.as_view(), name='testList'),
    url(r'minetester/(?P<slug>[\w-]+)/publiser/(?P<test_pk>[0-9]+)/$', views.TestListView.as_view(),
        name='testListPublish'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/slett/$', views.TestDeleteView.as_view(), name='testDelete'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/$', views.TestDetailView.as_view(), name='testDetail'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/(?P<grade_pk>[0-9]+)/klasse/$', views.TestDetailView.as_view(),
        name='testGradeDetail'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/(?P<group_pk>[0-9]+)/gruppe/$', views.TestDetailView.as_view(),
        name='testGroupDetail'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/publiser/$', views.TestCreateView.as_view(), name='testCreate'),
    url(r'test/(?P<test_pk>[0-9]+)/besvarelse/(?P<slug>[\w-]+)/$', views.AnswerListView.as_view(), name='answerDetail'),
    url(r'test/(?P<test_pk>[0-9]+)/besvarelse/public/(?P<user_id>[\w-]+)/$', views.AnswerListView.as_view(),
        name='answerDetailAnonymous'),
    url(r'test/(?P<test_pk>[0-9]+)/svar/$', views.AnswerCreateView.as_view(), name='answerCreate'),
    url(r'test/(?P<test_pk>[0-9]+)/eksporter/$', views.export_data, name='answerExport'),
    url(r'test/fullført/$', views.LinkSuccess.as_view(), name='answerFinished'),
    url(r'eksportering/$', views.ExportData.as_view(), name='exportData'),
    url(r'oppgaver/mappe/matistikk/$', views.DirectoryDetailView.as_view(), name='directoryRoot'),
    url(r'oppgaver/mappe/(?P<directory_pk>[0-9]+)/$', views.DirectoryDetailView.as_view(), name='directoryDetail'),
    url(r'oppgaver/mapper/slett/$', views.DirectoryDelete.as_view(), name='directoryDelete'),
    url(r'oppgaver/mapper/endre/$', views.DirectoryEdit.as_view(), name='directoryEdit'),
    url(r'oppgaver/mapper/flytt/$', views.DirectoryMove.as_view(), name='directoryMove'),
    url('r/oppgaver/logg/$', views.TaskLogView.as_view(), name='taskLog'),
    url('r/oppgaver/logg/slett/$', views.TaskLogDeleteView.as_view(), name='taskLogDelete'),
    url(r'test/(?P<answer_id>[0-9]+)/besvarelse/$', views.AnswerDetailView.as_view(), name='answerGET'),

]

matistikk/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from maths import views as mathViews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^matistikk/', include('maths.urls', namespace='maths')),
    url(r'^administrasjon/', include('administration.urls', namespace='administration')),
    url(r'^$', mathViews.IndexView.as_view(), name='index'),
    url(r'login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': '/'}, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maths/views.py
from django.views import generic
from django.contrib import messages
from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy, reverse
from .forms import CreateTaskForm, CreateCategoryForm, CreateTestForm, CreateAnswerForm, CreateTaskLog, \
    CreateTestAnswerForm
from .models import Task, MultipleChoiceTask, Category, GeogebraTask, Test, TaskOrder, TaskCollection, Answer, \
    GeogebraAnswer, Item, MultipleChoiceOption, InputFieldTask, InputField, Directory, TaskLog, ImageTask, TestAnswer
from braces import views
from django.http import JsonResponse
from administration.models import Grade, Person, Gruppe, School
import json
from django.db.models import Q
import django_excel as excel
from administration.views import AdministratorCheck, RoleCheck
import random
from django.http import HttpResponseRedirect
from django.conf import settings
from django.utils import formats
from django.utils import timezone


class AnswerCheck(views.UserPassesTestMixin):
    """
    Checks if the logged in user has privileges to see the answer.

     **UserPassesTestMixin:**
        Mixin from :ref:`Django braces` that check is the logged in user passes the test given in :func:`test_func`.
    """

    def test_func(self, user):
        """
            :param user: Person that has to pass the test.
            :return: True if the user logged in as an administrator.
        """
        test_id = self.kwargs.get('test_pk')
        if user.is_authenticated():
            role = [2, 3, 4]
            if user.role in role:
                return True
            elif user.role == 1:
                if self.kwargs.get('slug'):
                    answer_user = self.kwargs.get('slug')
                    if answer_user == user.username:
                        return True
                else:
                    if Person.objects.filter(id=user.id, tests__id=test_id).exists():
                        return True
                    elif Grade.objects.filter(person=user, tests__id=test_id).exists():
                        return True
                    elif Gruppe.objects.filter(persons=user, tests__id=test_id).exists():
                        return True
        else:
            test = Test.objects.get(id=test_id)
            if test.public:
                return True
        return False


class IndexView(LoginRequiredMixin, generic.TemplateView):
    """
    Class that displays the home page if logged in.

    **LoginRequiredMixin**
        Mixin from :ref:`Django braces` that check if the user is logged in.
    **TemplateView:**
        Inherits generic.Template that makes a page representing a specific template.
    """
    login_url = settings.LOGIN_URL
    template_name = 'maths/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        if self.request.user.role == 2:
            user = Person.objects.get(username=self.request.user.username)
            tests = Test.objects.filter(person=user)
            context['tests'] = tests
            context['lastanswers'] = TestAnswer.objects.filter(test__in=tests, user__isnull=False, status=3).order_by(
                '-id')
        if self.request.user.role == 4:
            context['answers'] = TestAnswer.objects.filter(status=3).count()
            context['users'] = Person.objects.count()
            context['tests'] = TaskCollection.objects.count()
            context['schools'] = School.objects.count()
            context['grades'] = Grade.objects.count()
            context['groups'] = Gruppe.objects.count()
            context['lasttests'] = Test.objects.all().order_by('-id')[:15]
            context['lastanswers'] = TestAnswer.objects.filter(status=3).order_by('-id')[:15]

        if self.request.user.role == 3:
            schools = School.objects.filter(school_administrator=self.request.user.id)
            persons = Person.objects.filter(grades__school_id__in=schools).distinct()
            context['persons'] = persons
            context['schools'] = schools
            grades = Grade.objects.filter(school__in=schools)
            context['grades'] = grades

        if self.request.user.role == 1:
            answeredTests = []
            test_answers = TestAnswer.objects.filter(user=self.request.user, status=3)
            tests = Test.objects.filter(
                Q(person=self.request.user) | Q(grade__in=self.request.user.grades.all()) | Q(
                    gruppe__in=self.request.user.gruppe_set.all())).distinct()
            answered = tests.filter(testanswer__in=test_answers).distinct().order_by('-answer__date_answered')
            for test in answered:
                if test not in answeredTests:
                    answeredTests.append(test)

            context['answered'] = answeredTests
            notanswered = []
            for test in tests:
                if test not in answeredTests:
                    notanswered.append(test)
            context['notanswered'] = notanswered
        return context


class EquationEditorView(generic.TemplateView):
    """
    Allows users to input math into the editor.

    **LoginRequiredMixin**
        Mixin from :ref:`Django braces` that check if the user is logged in.
    **TemplateView:**
        Inherits generic.Template that makes a page representing a specific template.
    """
    template_name = 'maths/equation_editor.html'


class TaskCreateView(AdministratorCheck, generic.CreateView):
    """
    Class that creates a task.

    :func:`AdministratorCheck`:
        inherited permission check, checks if the logged in user is an administrator.
    **CreateView:**
        Inherits Django's CreateView that displays a form for creating a object and
        saving the form when validated.
    """
    login_url = reverse_lazy('login')
    template_name = 'maths/task_form.html'
    form_class = CreateTaskForm
    success_url = reverse_lazy('maths:directoryRoot')

    def get_initial(self):
        if self.kwargs.get('directory_pk'):
            data = {
                'directory': self.kwargs.get('directory_pk')
            }
            return data
        else:
            directory = Directory.objects.get(parent_directory=None)
            data = {
                'directory': directory.id
            }
            return data

    def get_context_data(self, **kwargs):
        """
            Function that adds all category objects and a form to create a new category to the context without
            overriding it.

            :param kwargs: Keyword arguments.
            :return: Returns the updated context.
        """
        context = super(TaskCreateView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['categoryForm'] = CreateCategoryForm()
        return context

    def form_valid(self, form):
        """
        Function that checks if the submitted :ref:`CreateTaskForm` is correct. If correct adds the logged in user as
        the author and creates the task with its extra information.

        :param form: References to the filled out model form.
        :return: calls super with the new form.
        """
        task = form.save(commit=False)
        self.success_url = reverse_lazy('maths:directoryDetail', kwargs={
            'directory_pk': task.directory.id
        })
        task.author = self.request.user
        messages.success(self.request, 'Oppgave med navnet: ' + task.title + " ble opprettet.")
        variable_task = self.request.POST['variables']
        if variable_task:
            task.variableTask = True
        task.save()
        item = Item(task=task, variables=variable_task)
        item.save()
        if task.answertype == 2:
            options = self.request.POST['options']
            correct = self.request.POST['correct']
            questions = self.request.POST['questions']
            radio_or_check = self.request.POST['radioOrCheck']
            option_split = options.split('<--->')
            correct_split = correct.split('<--->')
            question_split = questions.split('|||||')
            radio_or_check_split = radio_or_check.split('|||||')
            x = 0
            for question in question_split:
                multiple_choice_task = MultipleChoiceTask(question=question, task=task)
                if radio_or_check_split[x] == 'true':
                    multiple_choice_task.checkbox = True
                else:
                    multiple_choice_task.checkbox = False
                multiple_choice_task.save()
                multiple_choice_options = option_split[0].split('|||||')
                multiple_choice_options_correct = correct_split[0].split('|||||')
                for i in range(0, len(multiple_choice_options)):
                    multiple_choice_option = MultipleChoiceOption(MutipleChoiceTask=multiple_choice_task,
                                                                  option=multiple_choice_options[i])
                    if multiple_choice_options_correct[i] == 'true':
                        multiple_choice_option.correct = True
                    else:
                        multiple_choice_option.correct = False
                    multiple_choice_option.save()
                option_split.pop(0)
                correct_split.pop(0)
                x += 1
        elif task.answertype == 4:
            input_questions = form.cleaned_data['inputQuestion']
            inputfield = form.cleaned_data['inputField']
            inputlength = form.cleaned_data['inputLength']
            inputcorrect = form.cleaned_data['inputCorrect']
            inputfraction = form.cleaned_data['inputFraction']
            inputfield_split = inputfield.split('<--->')
            inputlength_split = inputlength.split('<--->')
            inputcorrect_split = inputcorrect.split('<--->')
            inputfraction_split = inputfraction.split('<--->')

maths/templates/maths/category_list.html
<!--Extends the base.html file that includes different imports and the navbar-->
{% extends 'matistikk/base.html' %}
<!--Loads the tag library-->
{% load bootstrap3 %}
<!--Display django.contrib.messages as Bootstrap alerts-->
{% bootstrap_messages %}

{% block body %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1>Kategorier</h1>
            <div class="input-group">
                    <span class="input-group-addon">
                            <i class="fa fa-search"></i>
                        </span>
                <input type="text" class="form-control" id="search" onkeyup="categorySearch();"
                       placeholder="Søk etter kategori">
            </div>
        </div>
        <div class="panel-body">
            {% bootstrap_messages %}
            <div class="tab-content">
                {% if object_list %}
                    <table class="table table-hover table-striped table-responsive" id="categoryTable">
                        <thead>
                        <tr>
                            <th>Navn</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in object_list %}
                            <tr>
                                <td>{{ category }}</td>
                                <td><a class="btn btn-primary btn-sm"
                                       href="{% url 'maths:categoryUpdate' category.id %}">Oppdater</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h3>Ingen grupper lagt til</h3>
                {% endif %}
            </div>
        </div>
        <div class="panel-footer">
            <a class="btn btn-primary" href="{% url 'maths:categoryCreate' %}"><span
                    class="glyphicon glyphicon-plus"
                    aria-hidden="true"></span> Legg til kategori</a>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $(".alert-success").fadeTo(5000, 500).slideUp(500, function () {
                $('.alert-success').slideUp(500);
            });
        });
        /**
         * This function matches the text in the search field with the content in the table with all categories
         * and removes rows that don't match the search criteria.
         */
        function categorySearch() {
            var input, filter, table, tr, td, i, td1, td2;
            input = document.getElementById("search");
            filter = input.value.toUpperCase();
            table = document.getElementById("categoryTable");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
{% endblock %}

maths/templates/maths/equation_editor.html
<!DOCTYPE html>
<html>
<!--Loads staticfiles-->
{% load staticfiles %}
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'tinymce/js/tinymce/plugins/equationeditor/mathquill.min.js' %} "></script>
  <script type="text/javascript" src="{% static 'tinymce/js/tinymce/plugins/equationeditor/equation_editor.js' %} "></script>
    <script>var configurl = '{% static 'tinymce/js/tinymce/plugins/equationeditor/config.json' %}'</script>
  <link rel="stylesheet" type="text/css" href="{% static 'tinymce/js/tinymce/plugins/equationeditor/mathquill.css' %}">
  <link rel="stylesheet" type="text/css"     href="{% static 'tinymce/js/tinymce/plugins/equationeditor/equation_editor.css' %}">
</head>
<body class="equation-editor">
  <div class="cols">
    <div class="math-form col">
      <div class="button-bar"></div>

      <div class="math"></div>
    </div>
    <div class="button-groups col">
    </div>
  </div>
  <script type="text/javascript">
    var params = top.tinymce.activeEditor.windowManager.getParams();
    var existingLatex = params['existing_latex'];

    var equationEditor = new EquationEditor.EquationEditorView({
      $el: $('.equation-editor'),
      existingLatex: existingLatex,
      restrictions: top.tinymce.equationEditorRestrictions
    }).render();

    params['latexInput'] = equationEditor.input();
    top.tinymce.activeEditor.windowManager.setParams(params);
  </script>
</body>
</html>