administration/urls.py
from django.conf.urls import url
from . import views

app_name = 'administration'
urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/minside/$', views.MyPageDetailView.as_view(), name='myPage'),
    url(r'nybruker/$', views.PersonCreateView.as_view(), name='personCreate'),
    url(r'brukere/$', views.PersonListView.as_view(), name='personList'),
    url(r'brukere/(?P<slug>[\w-]+)/$', views.PersonDetailView.as_view(), name="personDetail"),
    url(r'brukere/oppdater/(?P<slug>[\w-]+)/$', views.PersonUpdateView.as_view(), name='personUpdate'),
    url(r'skoler/$', views.SchoolListView.as_view(), name='schoolList'),
    url(r'skoler/(?P<school_pk>[0-9]+)/$', views.SchoolDetailView.as_view(), name="schoolDetail"),
    url(r'lagskole/$', views.SchoolCreateView.as_view(), name='schoolCreate'),
    url(r'skoler/oppdater/(?P<school_pk>[0-9]+)/$', views.SchoolUpdateView.as_view(), name='schoolUpdate'),
    url(r'skoler/oppdater/(?P<school_pk>[0-9]+)/leggtilklasse/$', views.GradeCreateView.as_view(), name='gradeCreate'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/$', views.GradeDetailView.as_view(),
        name='gradeDetail'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/oppdater/$', views.GradeUpdateView.as_view(),
        name='gradeUpdate'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/leggtilelev/$', views.PersonCreateView.as_view(),
        name='gradeAddStudent'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/leggtillærer/$', views.PersonCreateView.as_view(role=2),
        name='gradeAddTeacher'),
    url(r'mineklasser/$', views.GradeListView.as_view(), name='gradeList'),
    url(r'grupper/$', views.GroupListView.as_view(), name="groupList"),
    url(r'gruppe/(?P<group_pk>[0-9]+)/$', views.GroupDetailView.as_view(), name='groupDetail'),
    url(r'grupper/nygruppe/$', views.GroupCreateView.as_view(), name='groupCreate'),
    url(r'brukere/slett/(?P<slug>[\w-]+)/$', views.PersonDeleteView.as_view(), name='personDelete'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/(?P<slug>[\w-]+)/slett/$',
        views.PersonDeleteView.as_view(), name='personDeleteGrade'),
    url(r'gruppe/(?P<group_pk>[0-9]+)/oppdater/$', views.GroupUpdateView.as_view(), name='groupUpdate'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/gruppe/$', views.GroupCreateView.as_view(),
        name='gradeGroupCreate'),
    url(r'skoler/(?P<school_pk>[0-9]+)/klasse/(?P<grade_pk>[0-9]+)/(?P<slug>[\w-]+)/$',
        views.PersonDetailView.as_view(), name='PersonDetailFromGrade'),
]

maths/urls.py
from django.conf.urls import url
from . import views

app_name = 'maths'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'nyoppgave/$', views.TaskCreateView.as_view(), name='createTask'),
    url(r'nyoppgave/mappe/(?P<directory_pk>[0-9]+)/$', views.TaskCreateView.as_view(), name='createTaskDirectory'),
    url(r'equationEditor/$', views.EquationEditorView.as_view(), name='equationEditor'),
    url(r'oppgaver/$', views.TaskListView.as_view(), name='taskList'),
    url(r'oppgaver/(?P<task_pk>[0-9]+)/$', views.TaskDetailView.as_view(), name='taskDetail'),
    url(r'oppgaver/(?P<task_pk>[0-9]+)/slett/(?P<item_pk>[0-9]+)/$', views.ItemDeleteView.as_view(), name='itemDelete'),
    url(r'oppgaver/oppdater/(?P<task_pk>[0-9]+)/$', views.TaskUpdateView.as_view(), name='taskUpdate'),
    url(r'kategorier/$', views.CategoryListView.as_view(), name='categoryList'),
    url(r'kategorier/ny/$', views.CategoryCreateView.as_view(), name='categoryCreate'),
    url(r'kategorier/(?P<category_pk>[0-9]+)/oppdater/$', views.CategoryUpdateView.as_view(), name='categoryUpdate'),
    url(r'lagtest/$', views.TaskCollectionCreateView.as_view(), name='taskCollectionCreate'),
    url(r'tester/$', views.TaskCollectionListView.as_view(), name='taskCollectionList'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/$', views.TaskCollectionDetailView.as_view(),
        name='taskCollectionDetail'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/oppdater/$', views.TaskCollectionUpdateView.as_view(),
        name='taskCollectionUpdate'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/slett/$', views.TaskCollectionDeleteView.as_view(),
        name='taskCollectionDelete'),
    url(r'minetester/(?P<slug>[\w-]+)/$', views.TestListView.as_view(), name='testList'),
    url(r'minetester/(?P<slug>[\w-]+)/publiser/(?P<test_pk>[0-9]+)/$', views.TestListView.as_view(),
        name='testListPublish'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/slett/$', views.TestDeleteView.as_view(), name='testDelete'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/$', views.TestDetailView.as_view(), name='testDetail'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/(?P<grade_pk>[0-9]+)/klasse/$', views.TestDetailView.as_view(),
        name='testGradeDetail'),
    url(r'tester/publisert/(?P<test_pk>[0-9]+)/(?P<group_pk>[0-9]+)/gruppe/$', views.TestDetailView.as_view(),
        name='testGroupDetail'),
    url(r'tester/(?P<taskCollection_pk>[0-9]+)/publiser/$', views.TestCreateView.as_view(), name='testCreate'),
    url(r'test/(?P<test_pk>[0-9]+)/besvarelse/(?P<slug>[\w-]+)/$', views.AnswerListView.as_view(), name='answerDetail'),
    url(r'test/(?P<test_pk>[0-9]+)/besvarelse/public/(?P<user_id>[\w-]+)/$', views.AnswerListView.as_view(),
        name='answerDetailAnonymous'),
    url(r'test/(?P<test_pk>[0-9]+)/svar/$', views.AnswerCreateView.as_view(), name='answerCreate'),
    url(r'test/(?P<test_pk>[0-9]+)/eksporter/$', views.export_data, name='answerExport'),
    url(r'test/fullført/$', views.LinkSuccess.as_view(), name='answerFinished'),
    url(r'eksportering/$', views.ExportData.as_view(), name='exportData'),
    url(r'oppgaver/mappe/matistikk/$', views.DirectoryDetailView.as_view(), name='directoryRoot'),
    url(r'oppgaver/mappe/(?P<directory_pk>[0-9]+)/$', views.DirectoryDetailView.as_view(), name='directoryDetail'),
    url(r'oppgaver/mapper/slett/$', views.DirectoryDelete.as_view(), name='directoryDelete'),
    url(r'oppgaver/mapper/endre/$', views.DirectoryEdit.as_view(), name='directoryEdit'),
    url(r'oppgaver/mapper/flytt/$', views.DirectoryMove.as_view(), name='directoryMove'),
    url('r/oppgaver/logg/$', views.TaskLogView.as_view(), name='taskLog'),
    url('r/oppgaver/logg/slett/$', views.TaskLogDeleteView.as_view(), name='taskLogDelete'),
    url(r'test/(?P<answer_id>[0-9]+)/besvarelse/$', views.AnswerDetailView.as_view(), name='answerGET'),

]

matistikk/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from maths import views as mathViews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^matistikk/', include('maths.urls', namespace='maths')),
    url(r'^administrasjon/', include('administration.urls', namespace='administration')),
    url(r'^$', mathViews.IndexView.as_view(), name='index'),
    url(r'login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': '/'}, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maths/forms.py
from django import forms
from .models import Task, Category, MultipleChoiceTask, GeogebraTask, Test, Answer, TaskLog
from administration.models import Person, Grade, School, Gruppe
from django.forms import inlineformset_factory


class CreateTaskForm(forms.ModelForm):
    """
    Form used to create a new task.

    :title: Title of the task.
    :text: Description of the task.
    :answertype: Answer details for the answer.
    :extra: Show extra extensions (geogebra).
    :reasoning: Show a field for an explanation of the answer.
    :category: Which categories the task fall under.
    :variableDescription: Description of the variables for GeoGebra.
    :reasoningText: Title for the reasoning answer-field.
    :options: Multiple choice options for the task.
    :base64: Geogebra string.
    :preview: PNG base64 string for GeoGebra.
    :create_new: Create new task or update the existing one.
    :questions: Questions for multiple-choice.
    :correct: Says which options are correct.
    :variables: Variables for Geogebra.
    :height: Dimension of the GeoGebra applet.
    :width: Dimension of the GeoGebra applet.
    :showMenuBar: Settings for GeoGebra - showMenuBar.
    :enableLabelDrags: Settings for GeoGebra - enableLabelDrags.
    :enableShiftDragZoom: Settings for GeoGebra - enableShiftDragZoom.
    :enableRightClick: Settings for GeoGebra - enableRightClick.
    """
    options = forms.CharField(max_length=100000, required=False)
    base64 = forms.CharField(max_length=200000, required=False)
    preview = forms.CharField(max_length=500000, required=False)
    create_new = forms.BooleanField(required=False)
    questions = forms.CharField(max_length=100000, required=False)
    correct = forms.CharField(max_length=100000, required=False)
    variables = forms.CharField(max_length=500, required=False)
    inputQuestion = forms.CharField(max_length=500, required=False)
    inputField = forms.CharField(max_length=500, required=False)
    inputLength = forms.CharField(max_length=500, required=False)
    inputCorrect = forms.CharField(max_length=500, required=False)
    inputFraction = forms.CharField(max_length=500, required=False)
    inputScore = forms.CharField(max_length=500, required=False)
    height = forms.CharField(max_length=100, required=False)
    width = forms.CharField(max_length=100, required=False)
    imageFile = forms.FileField(required=False)
    jsFile = forms.FileField(required=False)
    xmin = forms.FloatField(required=False)
    xmax = forms.FloatField(required=False)
    ymin = forms.FloatField(required=False)
    ymax = forms.FloatField(required=False)
    yratio = forms.FloatField(required=False)
    xstep = forms.FloatField(required=False)
    ystep = forms.FloatField(required=False)
    showMenuBar = forms.BooleanField(initial=False, required=False)
    enableLabelDrags = forms.BooleanField(initial=True, required=False)
    enableShiftDragZoom = forms.BooleanField(initial=True, required=False)
    enableRightClick = forms.BooleanField(initial=True, required=False)
    algebraInputField = forms.BooleanField(initial=False, required=False)
    radioOrCheck = forms.CharField(max_length=500, required=False)

    class Meta:
        """
            Bases the form on the Task model
        """
        model = Task
        fields = ['title', 'text', 'answertype', 'extra', 'reasoning', 'category', 'variableDescription',
                  'reasoningText', 'directory', 'answerText']


class CreateCategoryForm(forms.ModelForm):
    """
    Form used to create a new category.

    :category_title: Title of the category.
    """

    class Meta:
        """
           Bases the form on the Category model
        """
        model = Category
        fields = ['category_title']


class CreateTaskLog(forms.ModelForm):
    class Meta:
        model = TaskLog
        fields = ['text']


class CreateTestForm(forms.ModelForm):
    """
    Form used to create a new test.

    :persons: All the persons the test can be published to.
    :grades: All the grades the test can be published to.
    :schools: All the schools the test can be published to.
    :groups: All the groups the test can be published to.
    :order: The order of the tasks in test, if randomOrder is not True.
    :task_collection: The collection of the tasks (Base of the test).
    :randomOrder: Says if the order of the tasks should be random or in a given order.
    :published: Date the test is published.
    :dueDate: Due date for the test.
    """
    persons = forms.ModelMultipleChoiceField(queryset=Person.objects.filter(role__in=[1, 2]), required=False)
    grades = forms.ModelMultipleChoiceField(queryset=Grade.objects.all(), required=False)
    schools = forms.ModelMultipleChoiceField(queryset=School.objects.all(), required=False)
    groups = forms.ModelMultipleChoiceField(queryset=Gruppe.objects.all(), required=False)
    order = forms.CharField(max_length=10000)

    class Meta:
        model = Test
        fields = ['task_collection', 'randomOrder', 'published', 'dueDate', 'strictOrder']


class CreateAnswerForm(forms.ModelForm):
    """
    Form used to create a new answer.

    :base64answer: The base64 string from geogebra.
    :reasoning: The reasoning behind the answer.
    :text: The answer.
    :task: The task the answer matches to.
    """
    testanswer = forms.CharField()
    base64answer = forms.CharField(max_length=500000, required=False)
    reasoning = forms.CharField(max_length=32700, required=False)
    text = forms.CharField(max_length=32700, required=False)
    timespent = forms.FloatField(required=False)
    geogebradata = forms.CharField(max_length=500000, required=False)
    correct = forms.CharField(max_length=100, required=False)
    variables = forms.CharField(max_length=1000, required=False)
    matistikkanswer = forms.CharField(max_length=500, required=False)
    xmin = forms.FloatField(required=False)
    xmax = forms.FloatField(required=False)
    ymin = forms.FloatField(required=False)
    ymax = forms.FloatField(required=False)
    yratio = forms.FloatField(required=False)

    class Meta:
        model = Answer
        fields = ['reasoning', 'text', 'timespent', 'item']


class CreateTestAnswerForm(forms.Form):
    testAnswer_id = forms.CharField()

matistikk/views.py
from django.views import generic

from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.contrib.auth import login
from django.core.urlresolvers import reverse_lazy


class LoginView(generic.FormView):
    template_name = 'administration/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        login(self.request, form.get_user())
        self.request.session.set_expiry(0)
        return HttpResponseRedirect(self.get_success_url())

templates/matistikk/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Matistikk{% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'administration/style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="{% static 'administration/images/favico.png' %}">
    {% block head %}
    {% endblock %}
</head>
<body>
{% if request.user.role == 4 %}
    <!-- Super User Navbar-->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="pull left" href="{% url 'index' %}"><img src="http://bildr.no/image/Tjl2U25M.jpeg" width="240"
                                                                   height="50"/></a>
            </div>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home "></span></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false" id="overviewDropdown">Oversikt <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'administration:personList' %}" id="userOverview">Brukeroversikt</a>
                            </li>
                            <li><a href="{% url 'administration:schoolList' %}" id="schoolOverview">Skoleoversikt</a>
                            </li>
                            <li><a href="{% url 'administration:groupList' %}" id="groupOverview">Gruppeoversikt</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="{% url 'maths:directoryRoot' %}" id="taskOverview">Oppgaveoversikt</a></li>
                            <li><a href="{% url 'maths:taskCollectionList' %}" id="testOverview">Testoversikt</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'maths:taskCollectionCreate' %}" id="createTestBtn">Lag Test</a></li>
                    <li><a href="{% url 'maths:createTask' %}" id="createTask">Lag Oppgave</a></li>
                    <li><a href="{% url 'maths:exportData' %}" id="exportInfo">Eksportering</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'administration:myPage' request.user.username %}" id="myPageBtn"><i
                            class="fa fa-user-circle-o"
                            aria-hidden="true"></i> {{ request.user.first_name }} {{ request.user.last_name }}
                    </a></li>
                    <li><a href="{% url 'logout' %}" id="logout"><span class="glyphicon glyphicon-log-out"></span>Logg
                        ut</a></li>
                </ul>
            </div>
        </div>
    </nav>

{% elif request.user.role == 3 %}
    <!-- School Administrator User Navbar-->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="pull left" href="{% url 'index' %}"><img src="http://bildr.no/image/Tjl2U25M.jpeg" width="240"
                                                                   height="50"/></a>
            </div>
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home "></span></a></li>
                    <li><a href="{% url 'administration:personList' %}" id="userOverview">Brukeroversikt</a></li>
                    <li><a href="{% url 'administration:schoolList' %}" id="schoolOverview">Skoler</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'administration:myPage' request.user.username %}" id="myPageBtn"><i
                            class="fa fa-user-circle-o"
                            aria-hidden="true"></i> {{ request.user.first_name }} {{ request.user.last_name }}
                    </a></li>
                    <li><a href="{% url 'logout' %}" id="logout"><span class="glyphicon glyphicon-log-out"></span>Logg
                        ut</a></li>
                </ul>
            </div>
        </div>
    </nav>

{% elif request.user.role == 2 %}
    <!-- Teacher User Navbar-->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="pull left" href="{% url 'index' %}"><img src="http://bildr.no/image/Tjl2U25M.jpeg" width="240"
                                                                   height="50"/></a>
            </div>
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home "></span></a></li>
                    <li><a href="{% url 'administration:gradeList' %}" id="gradeOverview">Mine klasser</a></li>
                    <li><a href="{% url 'maths:testList' request.user.username %}" id="testOverview">Tilgjengelige
                        tester</a></li>
                    <li><a href="{% url 'administration:personList' %}" id="userOverview">Brukeroversikt</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'administration:myPage' request.user.username %}" id="myPageBtn"><i
                            class="fa fa-user-circle-o"
                            aria-hidden="true"></i> {{ request.user.first_name }} {{ request.user.last_name }}
                    </a></li>
                    <li><a href="{% url 'logout' %}" id="logout"><span class="glyphicon glyphicon-log-out"></span>Logg
                        ut</a></li>
                </ul>
            </div>
        </div>
    </nav>

{% else %}
    <!-- Student User Navbar-->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#mynavbar">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="pull left" href="{% url 'index' %}"><img src="http://bildr.no/image/Tjl2U25M.jpeg" width="240"
                                                                   height="50" alt="Home"/></a>
            </div>
            <div class="navbar-collapse collapse" id="mynavbar">
                <ul class="nav navbar-nav">

                    <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home "></span></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'administration:myPage' request.user.username %}" id="myPageBtn"><i
                            class="fa fa-user-circle-o"
                            aria-hidden="true"></i> {{ request.user.first_name }} {{ request.user.last_name }}
                    </a></li>
                    <li><a href="{% url 'logout' %}" id="logout"><span class="glyphicon glyphicon-log-out"></span> Logg
                        ut</a></li>
                </ul>
            </div>
        </div>
    </nav>

{% endif %}
{% block body %}
{% endblock %}
{% block modal %}
{% endblock %}
</body>
</html>